[package]
name = "tec"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "tec"
path = "src/bin/tec.rs"

[dependencies]
anyhow = "1.0.61"
env_logger = "0.9.0"
libaes = "0.6.2"
log = "0.4.17"
rand = "0.8.5"
